---
- name: Implementing handlers
  hosts: all
  tasks: 
     - name: Install apache2
       apt:
          name: apache2
          state: present
       notify: check url response
     - name: Edit the index.html file
       copy: 
          content: "welcome to iphone15  and iphone16"
          dest: /var/www/html/index.html
       notify: Restart apache2
  handlers:
     - name: Restart apache2
       service: 
          name: apache2
          state: restarted
     - name: check url response
       uri: 
          url: "{{item}}"
          status_code: 200
       with_items:
         - http://172.31.4.116
         - http://172.31.6.112
...            
