---
- name: Implementing play scope variables
  hosts: all
  vars: 
   - a: tomcat9
   - b: present
   - c: yes
  tasks:
   - name: Install/unisntall s/w using playscope variables
     apt:
      name: "{{a}}"  
      state: "{{b}}"
      update_cache: "{{c}}"
...

